#!/usr/bin/env python3
import numpy as np

# print('-----------------------------')
# print('numpy')
# print('-----------------------------')

# print('--------------------------')


# a = np.random.randint(1, 10, size= (3, 3))
# b = np.random.randint(1, 10, size= (3, 3))
# c=a.dot(b)
# print(c)
# print(c.shape)
# print(c.ndim)


# print('--------------------------')

# a = np.random.randint(1, 10, size= (4, 6))
# b = np.random.randint(1, 10, size= (6, 4))
# print('--------------------------')
# print(a)
# print('--------------------------')
# print(b)
# print('--------------------------')
# c=a.dot(b)
# print(c)
# print(c.shape)
# print(c.ndim)


# print('-----------------------------')



# a = np.array([[1, 2],[3, 4]])
# b = np.array([[5, 6],[7,8]])
# print('-----------------------------')
# print(a)
# print(b)
# print('-----------------------------')
# w = np.array([9, 10])
# v = np.array([11, 12])

# print('-----------------------------')
# print(w)
# print(v)
# print('-----------------------------')
# print('temporales')
# print('-----------------------------')
# temp1=np.dot(w,v)
# print(temp1)
# print(type(temp1))
# print(temp1.ndim)
# print('-----------------------------')
# temp2=w.dot(v)
# print(temp2)
# print(type(temp2))
# print(temp2.ndim)
# print('-----------------------------')
# print('temporales')
# print('-----------------------------')
# temp3=a.dot(v)
# temp4=np.dot(a,v)

# print(temp3)
# print(type(temp3))
# print(temp3.ndim)
# print('-----------------------------')
# print(temp4)
# print(type(temp4))
# print(temp4.ndim)
# print(temp4.shape)
# print('-----------------------------')


# a = np.array([[1, 2],[3, 4]])
# print(a)
# result=np.sum(a)
# print('el resultado de la suma de todos los elementos dentro de la matriz es:', result )
# print('-----------------------------')
# print('suma por filas y columnas')
# print('-----------------------------')
# a = np.random.randint(1, 10, size= (15, 15))
# print('matriz aleatoria')
# print('-----------------------------')
# print(a)
# print('-----------------------------')
# # m = a[:15, :1]
# # print(m)
# res=np.sum(a,axis=0)
# print('suma de columnas')
# print(res)
# print('promedio de columnas')
# resavg=np.average(a,axis=0)
# print(np.round(resavg,2))
# print('-----------------------------')
# res=np.sum(a,axis=1)
# print('suma de filas')
# print(res)
# print('promedio de filas')
# resavg=np.average(a,axis=1)
# print(np.round(resavg,2))
# print('-----------------------------')
# print('-----------------------------')
# a = np.random.randint(1, 21, size= (4, 4))
# print(a)
# print('-----------------------------')
# print(a.T)
# print('-----------------------------')
# print('-----------------------------')
# a = np.random.randint(1, 21, size= (3, 4))
# print(a)
# print('-----------------------------')
# print(a.T)


x = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
v = np.array([1, 0, 1])
emptymatrix=np.empty_like(x)
# add_m=np.add(x,v)
# print(add_m)

print(x)
print(v)
print(x.shape)
print('rows',x.shape[0])
for i in range (x.shape[0]):
    emptymatrix[i,:]=x[i,:]+v
print(emptymatrix)



vv=np.tile(v,[4,1])
print(vv)
print(v+vv)

print('-----------------------------')
print('hstack y vstack')
print('-----------------------------')
a = np.random.randint(1, 10, size= (4, 6))
b = np.random.randint(1, 10, size= (4, 6))
print(a)
print('-----------------------------')
print(b)
print('-----------------------------')
print('horizontal')
print('-----------------------------')

resul=np.hstack((a,b))
print(resul)
print('-----------------------------')
print('vertical')
print('-----------------------------')
resul=np.vstack((a,b))
print(resul)